### ISSUE TITLE
Add a full example to the readme

### ISSUE THREAD

**Issue by rabbadab** [custom-components/sensor.avanza_stock#104]
Hi! I love the integration but I can't understand how some of the configurations work and what data I should put in. 
For example: 
I'm trying to have my stock in SEK but it's a US stock. What should I put in the conversion_currency? 
On purchase_price in Avanza I only get the price in SEK is that what I put in there if I figure out the conversion_currency?

**Comment by claha** [comment]
I should definetly add a full example, will try and do it asap :) the id to use for conversion currency is 19000 (https://www.avanza.se/index/om-indexet.html/19000/usd-sek). You are correct about the purchase price.

Unfourtenately there is a bug in the profit/loss when using conversion currency but I am trying to find some time to fix it soon. (https://github.com/custom-components/sensor.avanza_stock/issues/91).

**Comment by rabbadab** [comment]
Haha tack! This will make is so much better for me to just look at my HA and not having to login into Avanza everyday
That URL with the currency was the one I was looking for ;)
