### ISSUE TITLE
Add version key

### ISSUE THREAD

**Issue by ronnydahl** [custom-components/sensor.avanza_stock#110]
Haven't seen this message in HA log before. Got it today after I installed core-2021.3.3.

No 'version' key in the manifest file for custom integration 'avanza_stock'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'avanza_stock

**Comment by claha** [comment]
Should be fixed in 593413b31ca605786af77740ed7548aa1fe1c731, I just need to release a new version and the warning should disappear if you update (you could also install master). I will release a new version once I have tested and merged PR #109, hopefully later today.

**Comment by claha** [comment]
#109 merged, closing issue.
