### ISSUE TITLE
Expose historical NAV values

### ISSUE THREAD

**Issue by ronnydahl** [custom-components/sensor.avanza_stock#112]
Is it possible to fetch historical NAV values for one or more given instruments from any of the Avanza APIs?

**Comment by ronnydahl** [comment]
I notice that they seemingly populate the chart with data from: https://www.avanza.se/ab/component/highstockchart/getchart/orderbook

Request body (POST):
{
	"orderbookId": 769140,
	"chartType": "AREA",
	"widthOfPlotContainer": 558,
	"chartResolution": "MINUTE",
	"navigator": false,
	"percentage": false,
	"volume": false,
	"owners": false,
	"start": "2020-08-26T05:37:41.710Z",
	"end": "2020-11-15T23:24:05.353Z",
	"ta": [],
	"compareIds": [
		19002
	]
}

I would assume this is exposed through an API too.

**Comment by claha** [comment]
Sounds nice but not sure if I can change the sensor value "in the past", and putting this in an attribute just seems strange to me...

**Comment by claha** [comment]
Out of scope
