### ISSUE TITLE
Unable to add topics

### ISSUE THREAD

**Issue by claha** [custom-components/sensor.avanza_stock#117]
I'm not able to add topics to this repo, there should be gear icon next to about. I can see it in my own repos but not in this organization.
![image](https://user-images.githubusercontent.com/9336788/116388697-64492d00-a81c-11eb-9693-7a1b51a335c8.png)

@ludeeus @iantrich Seems you two are the owners of the organization so perhaps you can help me out?

**Comment by ludeeus** [comment]
github changed some stuff a while back, should be possible now
