### ISSUE TITLE
No sensor 

### ISSUE THREAD

**Issue by duffel90** [custom-components/sensor.avanza_stock#123]
I get no sensor after the example configuration. A restart don't solve the problem. What do I wrong?

Version | core-2021.8.6
Installationstyp | Home Assistant Core
Entwicklung | false
Supervisor | false
Docker | false
user | homeassistant
Virtuelle Umgebung | true
Python-Version | 3.8.11

I added avanza_stock with HACS.

In my sensor.yaml I added
- platform: avanza_stock
  stock:
    - id: 5361
      name: Avanza Bank Holding
    - id: 735055
      name: Vonovia
    monitored_conditions:
    - totalVolumeTraded
    - totalValueTraded

**Comment by claha** [comment]
Do you get any errorw/warnings in the log. The config seems to be ok but could you please format it as code so I can be sure.

**Comment by duffel90** [comment]
Hey claha, sorry for the long waiting time.
the only log warning with avanza is.

2021-09-07 00:08:44 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration avanza_stock which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by claha** [comment]
That warning is expected, could you perhaps paste your sensor.yaml in a code block so I can check it?

**Comment by duffel90** [comment]
- platform: avanza_stock
  stock:
    - id: 5361
      name: Avanza Bank Holding
    - id: 735055
      name: Vonovia
      monitored_conditions:
      - totalVolumeTraded
      - totalValueTraded

**Comment by duffel90** [comment]
`- platform: avanza_stock
  stock:
    - id: 5361
      name: Avanza Bank Holding
    - id: 735055
      name: Vonovia
      monitored_conditions:
      - totalVolumeTraded
      - totalValueTraded`

**Comment by duffel90** [comment]
`- platform: avanza_stock`
`  stock:`
`    - id: 5361`
`      name: Avanza Bank Holding`
`    - id: 735055`
`      name: Vonovia`
`      monitored_conditions:`
`      - totalVolumeTraded`
`      - totalValueTraded`

**Comment by duffel90** [comment]
[sensors.yaml.txt](https://github.com/custom-components/sensor.avanza_stock/files/7149805/sensors.yaml.txt)

**Comment by duffel90** [comment]
[sensors.yaml.txt](https://github.com/custom-components/sensor.avanza_stock/files/7149807/sensors.yaml.txt)

**Comment by duffel90** [comment]
I don't know what I done, but now it works

**Comment by claha** [comment]
Monitoree conditions is intendent to much in the file you attached
