### ISSUE TITLE
Support "long term statistics"

### ISSUE THREAD

**Issue by yonz2** [custom-components/sensor.avanza_stock#124]
In order to display some statistics on the HA Dashboard, support for the HA Long term Statistcs function is needed. See also: https://www.home-assistant.io/more-info/statistics/ and https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by claha** [comment]
I've tried setting the state class (STATE_CLASS_TOTAL), I wanted to set the device class as well (DEVICE_CLASS_MONETARY) but that combination is not allowed according to the documentation. But whatever I try I am not able to add it to a statistics card. Any ideas?

**Comment by claha** [comment]
Not sure this can be done I don't really see the usecase
