### ISSUE TITLE
Entity implements device_state_attributes

### ISSUE THREAD

**Issue by jamespreedy** [custom-components/sensor.avanza_stock#130]
Hiya, thanks for your great work with this custom_component.

In my logs, Home Assistant is telling me to report the below to you - hope this is the correct place.

`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549 
First occurred: 7:07:31 am (2 occurrences) 
Last logged: 7:07:32 am

Entity sensor.apple (<class 'custom_components.avanza_stock.sensor.AvanzaStockSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.gbp_to_usd (<class 'custom_components.avanza_stock.sensor.AvanzaStockSensor'>) implements device_state_attributes. Please report it to the custom component author.
`

System information below.

## System Health

version | core-2021.12.9
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.88
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4993
Installed Version | 1.19.2
Stage | running
Available Repositories | 996
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 1 February 2022, 12:00 am
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-west-2-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | failed to load: timeout

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 222.8 GB
disk_used | 21.0 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), SSH & Web Terminal (10.0.1), Check Home Assistant configuration (3.9.0), SQLite Web (3.2.0), Duck DNS (1.14.0), Z-Wave JS to MQTT (0.32.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 11
mode | storage

</details>

**Comment by claha** [comment]
Hi, it has been fixer in #129. I just need to make a new release and then it should shortly be available in hacs. Before I do the release I want to go through the current issues and see if there are som easy fixes. Hopefully I can manage that today

**Comment by jamespreedy** [comment]
Brilliant - you're way ahead of me!
Thanks again for all your great work. 🍺
