### ISSUE TITLE
Broken after 2022.3.6 update

### ISSUE THREAD

**Issue by bkr1969** [custom-components/sensor.avanza_stock#133]
Stock price is not updating.

**Comment by claha** [comment]
I'm currently om 2022.3.5 which works fine. Anything in the logs? I'll see if I can try .6 soon.

**Comment by bkr1969** [comment]
Now I seem to be getting data again but it's several hours behind.  Any way to change the offset?

**Comment by claha** [comment]
The api returns what is available, no way to get historical data. So of the api is behind several hours, I don't see how that can be since I guess they use the same for displaying data on their site, there is nothing we can do.
