### ISSUE TITLE
Long-term statistics

### ISSUE THREAD

**Issue by filikun** [custom-components/sensor.avanza_stock#139]
It seems that the sensor generated by this integration does not function as a a [long-term satistics](https://data.home-assistant.io/docs/statistics/) sensor. Is it possible to make that work? So that one can pull history longer than the purge on the recorder (Love those apex charts).

**Comment by claha** [comment]
I've made some attempts to add this some months ago vit was not successfull, maybe there are more examples available now 😊 pull requests are welcome 😀

**Comment by claha** [comment]
I've figured it out, I was using an old (perhaps deprecated) base class. Once I tried the new one statistics started working, I can hopefully merge it this weekend :)
