### ISSUE TITLE
new functionality: option to add multiple portfolio holders

### ISSUE THREAD

**Issue by eddysteurs** [custom-components/sensor.avanza_stock#148]
would it be possible to add a portfolio holder  into the entities, I have 2 holders and in both I have some same stocks (one portfolio is self managed, the other by a external portfolio management company). In the current setup I can not have the same stock (e.g. Microsoft) in both portfolios because it is based only on avanza id number

**Comment by oli737** [comment]
I have requested the same in #136.
Same topic.

**Comment by claha** [comment]
As I've written in the other thread, I will not change the unique id since it will be a breaking change for most people but you can always modify the function yourself to make it work

Example
```
    @property
    def unique_id(self):
        """Return the unique id."""
        return f"{self._stock}_{self._shares}_stock"
```

**Comment by claha** [comment]
If you have the same stock and same amount of shares the example I gave you wont work, you would need something more then to make it unique. You could also just remove the function competely I guess
