### ISSUE TITLE
Attributes unknown in the info retrieved 

### ISSUE THREAD

**Issue by matzzzz** [custom-components/sensor.avanza_stock#149]
Hi,
Since a few months ago, the attributes in the retrieved data have been unknown (see below snip) I thought it was som problem with my installation, but now I have tried it on another HA instans and get the same result. I'm happy for any help :-)
Best regards
Matz

<img width="370" alt="avanza-attribute-issue" src="https://user-images.githubusercontent.com/34838972/210523227-422679f1-873f-444c-8327-6ce4a4ba5493.png">

**Comment by claha** [comment]
Just released v1.1.0 that uses the new api. State and the change/changePercent attributes should at least work now :slight_smile:

Please let me know if you find issues!
