### ISSUE TITLE
Nan error after upgrade from v1.2.0 to v1.3.0

### ISSUE THREAD

**Issue by rinkassie** [custom-components/sensor.avanza_stock#161]
asml-holding-nv with stock id 732279 gives NAN error after update to V1.3.0. 
Reverting to V1.2.0 gives the correct values again.

**Comment by claha** [comment]
Is the atate NAN or some attributes? Are there any errors in the homeassistant log?

**Comment by claha** [comment]
I copied your config and it works fins for me, I am on version 1.4.0 though but that shouldn't matter for the state. Could you please confirm that the state is also NaN in "Developer tools -> States", so that it is not some big with that card? What card is it?

**Comment by manofpants** [comment]
@claha good call on the checking the states. Apparently at some point duplicate sensors were created and I found that the entity is now sensor.gme_2 and such. Why that happened I don't know :)

**Comment by rinkassie** [comment]
FYI, 

I discovered after the upgrade that a new sensor was made (in my case sensor.asml_2) and the original was greyed out. I found it by looking in the 'States' section of the 'Developer Tools'. 

The new sensor gave no errors and had valid results. But as it was unexpected I decided to look a bit further and searched for the new sensor in the core.entity_registry. 

I found multiple entries of the original one (sensor.asml_1 was also present), deleted them all and also temporarily disabled the lovelace references to the original one (sensor.asml) and restarted HA. 

Afterwards the original sensor was working again. Today I did the update to 1.4.0. and it gave me no issues. 

I don't kniw if something similar has happened in your case, but it might be useful to check the Developer Tools States section.. 

Hope to help... 

⁣Get TypeApp for Android ​

**Comment by manofpants** [comment]
I did the same, but instead just deleted the grey ones, removed the integration, rebooted, removed the "new" ones (with _2), commented out the sensor declarations in yaml, re-installed the integration, rebooted, un-commented, rebooted and everything's back to normal now lol

:)

**Comment by claha** [comment]
Happy to hear that things seems to work again (after some reboots and editing :)). I think it has to do with that I needed to change how the unique id was generated because of #136
