### ISSUE TITLE
Is this still working or is Avanza API just down?

### ISSUE THREAD

**Issue by mgretz** [custom-components/sensor.avanza_stock#168]
Home Assistant Component doesnt get any data.

But if i call the Avanza API directly in my browser i get an 404 http error:

https://www.avanza.se/_api/market-guide/exchangetradedfund/1064101

Are there any changes on the API or is it just down?

**Comment by claha** [comment]
Stock endpoint still seems to work, hopefully just the etf endpoint. I'll try and see if I can find some time this weekend, should be easy to see if something has changed.

https://www.avanza.se/_api/market-guide/stock/1064101

**Comment by claha** [comment]
Took some time instead 😆 endpoint has changed
https://www.avanza.se/_api/market-etf/1064101

**Comment by claha** [comment]
Underlying package has been updated, I will update manually and run for a day or two beefore pushing it here

**Comment by teddy-rpi** [comment]
Hi claha, any news on this issue? Is the fix stable? Can I help testing?

**Comment by claha** [comment]
Should be working now in the new release (1.5.0). Let me know if it doesn't.

**Comment by teddy-rpi** [comment]
Confirmed, thanks. Everything is back to normal!
