### ISSUE TITLE
error on avanza server

### ISSUE THREAD

**Issue by eddysteurs** [custom-components/sensor.avanza_stock#182]
since yesterday (22/7) I get the following error
![image](https://github.com/user-attachments/assets/4f0c52cf-f8cf-42ff-ab2d-9dfd70f52a67)

Maybe it is down on avanza side or did they change something?

**Comment by claha** [comment]
API seems to be working right now at least, perhaps tour asset has changed id. Replace the number at then of this URL to check https://www.avanza.se/_api/market-guide/stock/5311

**Comment by eddysteurs** [comment]
working again
