### ISSUE TITLE
Calculate Gain or Loss if number of Shares is input

### ISSUE THREAD

**Issue by mrneilix** [custom-components/sensor.avanza_stock#40]
[https://github.com/mrneilix/sensor.avanza_stock](url)

So I have very little python knowledge, but in case you want to add this feature, I forked your repo to add a gain/loss calculation per stock if the number of shares are in the config

**Comment by claha** [comment]
That would be a good thing to add. You can make a pull request if want to so I can review it or let me know if I should just "steal" your implementation. 

On vacation this and the next week so response might be a little slow :)

**Comment by claha** [comment]
Will also add gain_loss_xxx based on priceFiveYearsAgo
priceOneMonthAgo
priceOneWeekAgo
priceOneYearAgo
priceSixMonthsAgo
priceThreeMonthsAgo
priceThreeYearsAgo

**Comment by imist** [comment]
An attribute for total value per stock would be nice too, i.e. price * shares. ;-)
