### ISSUE TITLE
Add config flow and break out in single sensors.

### ISSUE THREAD

**Issue by eifinger** [custom-components/sensor.avanza_stock#47]
Following your call for ideas in the forum.
You could break out the attributes into sensor entities of their own.
This offers 2 advantages:
1. You can build a config flow so this integration is usable via UI. If a user does not want to have all monitored conditions he can disable the single entities.

2. Upon a state change no really big state object is saved to the recorder(database). This would speed up all database queries and lower the size consumed.

**Comment by claha** [comment]
I guess this api call could be very useful when using config, since it can find the id for us
https://www.avanza.se/_mobile/market/search?query=avanza%20bank&limit=100

**Comment by claha** [comment]
Will not be done for this component, if done it will be in a new similar component
