### ISSUE TITLE
Since we are on the subject of possible enhancements - Purchase Price

### ISSUE THREAD

**Issue by VarenDerpsAround** [custom-components/sensor.avanza_stock#74]
Currently I use a very long and very difficult solution for displaying my current positions in specific stocks. 

It goes like this

Template_sensor_price = attr_sensor_stock:price

Template_sensor_value = template_sensor_price * stock_position_value.

Stock_position_value = !secret SnapStockPositon

Do you follow? Essentially, if so could have the attribute of purchase price in the sensor, you could have one additional attribute of "current position." 

Follow?

Just an idea for a sick enhancement that I think could benefit quite a few of us. 

I use secrets for the stock position value, the number of a stock I have because itst made it easier to adjust all the different values in one place.

Let me know what you think and apologies for any typos or bad formatting. I am on mobile, and saw you were live on git hub, and had the idea. Cheers.

**Comment by claha** [comment]
Good idea, not sure I understand your calculations. So given that we add an optional `purchase_price` option, I'm all for that and it is easy to add and the config below.

```yaml
platform: avanza_stock
stock: 1234
shares:100
purchase_price: 10.0
```
Would you like a new attribute `profit_loss` and `total_profit_loss` which would be calculated
`profit_loss = current_price - purchase_price`
`total_profit_loss = shares * profit_loss`?

I need to look into what the proper financial term for this is, maybe `current_position` as you mention is the correct one.

Please met me know if I understand you correctly :)

**Comment by VarenDerpsAround** [comment]
You got it!!! Spot on with the translation of my gibberish!
