### ISSUE TITLE
-Typoggraphical error- Got the New update working as expected, but I found something you might have slightly overlooked perhaps?

### ISSUE THREAD

**Issue by VarenDerpsAround** [custom-components/sensor.avanza_stock#76]
"totaProfitLoss" perhaps should be "tota(l)ProfitLoss?" It seems the L in total was lost? or perhaps that was on purpose? Just happened to see it when I was setting up my custom sensors. 

Cheers.

**Comment by claha** [comment]
Thanks, will be fixed before I do a release. I want to include #73 before I release a new version.
