### ISSUE TITLE
 Platform error sensor.avanza_stock - No module named 'pyavanza'

### ISSUE THREAD

**Issue by ikrowni** [custom-components/sensor.avanza_stock#85]
Getting this error after installing avanza stock through hacs. ive configured the basic sensor as described but get this error

**Comment by claha** [comment]
It should get installed automatically once addded by hacs. When starting HA there should be a line in the log that says that it is trying to install a specific version of pyavanza. Could you try and restart HA and look for that?

If that does not work could you please post your full configuration of avanza_stock and the error you receive.

**Comment by ikrowni** [comment]
Okay it seems to be fixed thanks for the support
