### ISSUE TITLE
Sort by not working as expected

### ISSUE THREAD

**Issue by gsolem** [custom-components/sensor.avanza_stock#86]
Sort by is not sorting as expected. E.g. attached list is set to sort by `changePercent-` but as you can see it is not working out very well. 

Aksje | Last | Change % | Last updated
-- | -- | -- | --
KID | 74.60 | 4.48 % | 8/3/2020, 9:49:39 PM
MOWI | 169.95 | 3.75 % | 8/3/2020, 9:59:04 PM
GSF | 94.00 | 2.17 % | 8/3/2020, 9:58:57 PM
TOM | 381.00 | 2.06 % | 8/3/2020, 9:59:05 PM
ENDUR | 1.52 | 14.72 % | 8/3/2020, 9:52:41 PM
VEI | 125.60 | 1.95 % | 8/3/2020, 9:50:36 PM
STB | 50.02 | 1.21 % | 8/3/2020, 9:58:21 PM
AKER | 386.20 | 0.94 % | 8/3/2020, 9:58:48 PM
NEL | 18.74 | 0.40 % | 8/3/2020, 9:59:04 PM
ASA | 114.00 | -1.30 % | 8/3/2020, 9:38:34 PM
HEX | 46.82 | -1.10 % | 8/3/2020, 9:55:56 PM
NSKOG | 28.00 | -0.36 % | 8/3/2020, 9:59:12 PM

Above is when using the modify to round to a fixed nos. of decimals, e.g. `modify: parseFloat(x).toFixed(2)`. Without using modify on the column, it is sorting just fine:

Aksje | Last | Change % | Last updated
-- | -- | -- | --
ENDUR | 1.52 | 14.72 % | 8/3/2020, 9:52:41 PM
KID | 74.60 | 4.48 % | 8/3/2020, 9:49:39 PM
MOWI | 169.95 | 3.75 % | 8/3/2020, 9:59:04 PM
GSF | 94.00 | 2.17 % | 8/3/2020, 9:58:57 PM
TOM | 381.00 | 2.06 % | 8/3/2020, 9:59:05 PM
VEI | 125.60 | 1.95 % | 8/3/2020, 9:50:36 PM
STB | 50.02 | 1.21 % | 8/3/2020, 9:58:21 PM
AKER | 386.20 | 0.94 % | 8/3/2020, 9:58:48 PM
NEL | 18.74 | 0.4 % | 8/3/2020, 9:59:04 PM
NSKOG | 28.00 | -0.36 % | 8/3/2020, 9:59:12 PM
HEX | 46.82 | -1.1 % | 8/3/2020, 9:55:56 PM
ASA | 114.00 | -1.3 % | 8/3/2020, 9:38:34 PM

**Comment by claha** [comment]
Your Change % column seems to be a string, so given that it is sorted correctly. There is no functionality in this component to sort lists so I'm not sure how I can help you. The changePercent attribute of an avanza_stock sensor is a float so you must be doing something with the data. Please provide more info, configuration etc. if you need further help.

**Comment by gsolem** [comment]
@claha You are right, actually I believe this is related to the flex-table component in home assistant and not the Avanza sensor. Sorry for the confusion, I will follow up under the table card component.
