### ISSUE TITLE
Reverse Conversion Currency

### ISSUE THREAD

**Issue by fabir-git** [custom-components/sensor.avanza_stock#87]
It would be nice to have a "reverse conversion currency" flag.

Example: I want to show a stock in EUR that has USD but avanza only has a conversion for EUR->USD so this does not work at the moment.

If we would have a "reverse flag" it could divide the stockprice through the conversion factor instead of multiplying it so there are more currency options.

**Comment by mbedk** [comment]
+1 for this feature. Currently there is no conversion between NOK and DKK.

Also would be nice to define a default currency to include currency loss/gain.

Btw this integration is awesome! Should be the default in HA.

**Comment by claha** [comment]
@mbedk Perhaps then we would like to be able to chain currency conversions (and possibly invert each one if needed), i.e. NOK->SEK followed by SEK->DKK?

Could you please elaborate on the default currency, I don't really understand what you are looking for. Preferrebly create a new issue for it.

Thanks! 😁 I have started to create a minimal version of this to be merged into HA, hopefully I can get that in soon and then start adding all the features from here.

**Comment by fabir-git** [comment]
Thank you for your great work, claha!

**Comment by claha** [comment]
Is it only the unit_of_measurement that seems wrong or the value as well?

**Comment by fabir-git** [comment]
it is only the unit of measurement, the value is right

**Comment by claha** [comment]
A quick look at the code and it seems I don't change the unit when using the invert flag, I will reopen the issue.

**Comment by claha** [comment]
The currency retrieved from the api always seems to SEK, need to parse the name of the index instead which always seems to be "FROM/TO" and use that instead.
