### ISSUE TITLE
Currency Gain/Loss

### ISSUE THREAD

**Issue by mbedk** [custom-components/sensor.avanza_stock#91]
This add-on is currently able to calculate the gains and losses based on GA price and number of stocks purchased.

However this does not take into account the loss/gain in currency.

Example My local currency is DKK. If I purchase a stock in Norway, there is a currency exchange happening at the time of the purchase. While I hold this stock, the currency between NOK and DKK changes. If I were to sell this stock after 6 months, I would not only have gained/lost the increase/decrease value in the stock but also the currency.

**Comment by claha** [comment]
@mbedk Will this not be handled if you set the purchase_price in DKK?

Example: 
Buy 1 stock A for 2DKK (this is the purchase_price) the stock is actually bought in NOK and at that day the conversion rate is 1:1 (to make it simple). They next day the value of the stock does not change but the conversion rate changes so now you need 2DKK for 1NOK. Purchase price is till 2DKK but current value is 4DKK.

Please correct me if I'm wrong :)

**Comment by fabir-git** [comment]
I think this does not work at the moment. The results are way off if I try this.

Example: stock in dollar, conversion to euro. Purchase price in euro -> Profit is way to high.

**Comment by claha** [comment]
Hi,

A quick glance at the code and it does not seem to handle the conversion
rate in the profit/loss calculation. I will have a look at it.

Thanks for finding the bug :)

Best regards,
Claes

Den tors 7 jan. 2021 17:18fabir-git <notifications@github.com> skrev:
