### ISSUE TITLE
Stock indices show currency sek

### ISSUE THREAD

**Issue by fabir-git** [custom-components/sensor.avanza_stock#99]
It seems like the unit for stock indices like the DAX is reported in 'SEK' instead of points.

**Comment by claha** [comment]
Yes this is correct. The api returns SEK as the currency, not sure why. The only option I see is to add a config option to set the unit_of_measurement manually. Would this suffice?

**Comment by fabir-git** [comment]
That would be fine. Seems we have found a bug in their api.
Thank you claha :)
